import type { Transaction, User } from '../types';
import XLSX from 'xlsx-js-style';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const downloadExcel = (transactions: Transaction[], user: User, filename: string = 'Fintrix_Financial_Report') => {
  const reportDate = new Date().toLocaleDateString('en-IN');

  // Prepare data rows
  const titleStyle = {
    font: { bold: true, size: 14, color: { rgb: "197ADC" } },
    alignment: { horizontal: 'center' }
  };

  const infoStyle = {
    font: { italic: true, size: 10, color: { rgb: "64748B" } },
    alignment: { horizontal: 'center' }
  };

  const headerStyle = {
    font: { bold: true, color: { rgb: "FFFFFF" } },
    fill: { fgColor: { rgb: "197ADC" } },
    alignment: { horizontal: 'center' }
  };

  const centerStyle = { alignment: { horizontal: 'center' } };
  const rightStyle = { alignment: { horizontal: 'right' } };

  // Create worksheet
  const ws = XLSX.utils.json_to_sheet([]);

  // Add professional header metadata (Rows 1-3)
  XLSX.utils.sheet_add_aoa(ws, [
    [{ v: 'FINTRIX FINANCIAL REPORT', s: titleStyle }],
    [{ v: `Generated By: ${user.firstName} ${user.lastName}`, s: infoStyle }],
    [{ v: `Report Date: ${reportDate}`, s: infoStyle }]
  ], { origin: 'A1' });

  // Add Table Headers at Row 5
  const headers = ['S.No', 'Date', 'Description', 'Category', 'Type', 'Amount (Rs.)'];
  XLSX.utils.sheet_add_aoa(ws, [
    headers.map(h => ({ v: h, s: headerStyle }))
  ], { origin: 'A5' });

  // Add Transaction Data (starting from Row 6)
  const rows = transactions.map((tx, index) => [
    { v: index + 1, s: centerStyle },
    { v: tx.date, s: centerStyle },
    { v: tx.description },
    { v: tx.category },
    { v: tx.type.toUpperCase(), s: centerStyle },
    { v: tx.amount, s: rightStyle }
  ]);
  XLSX.utils.sheet_add_aoa(ws, rows, { origin: 'A6' });

  // Centering & Merging: Merge A1:F1, A2:F2, A3:F3
  ws['!merges'] = [
    { s: { r: 0, c: 0 }, e: { r: 0, c: 5 } },
    { s: { r: 1, c: 0 }, e: { r: 1, c: 5 } },
    { s: { r: 2, c: 0 }, e: { r: 2, c: 5 } }
  ];

  // Dynamic Auto-Width Calculation
  const columnWidths = headers.map((header, i) => {
    const headerLen = header.length;
    const maxDataLen = transactions.reduce((max, tx) => {
      let val = '';
      if (i === 0) val = (transactions.indexOf(tx) + 1).toString();
      else if (i === 1) val = tx.date;
      else if (i === 2) val = tx.description;
      else if (i === 3) val = tx.category;
      else if (i === 4) val = tx.type;
      else if (i === 5) val = tx.amount.toString();

      return Math.max(max, val.length);
    }, headerLen);
    return { wch: Math.max(maxDataLen + 2, 10) };
  });
  ws['!cols'] = columnWidths;

  // Create workbook and download
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Transactions');
  XLSX.writeFile(wb, `${filename}_${new Date().toISOString().split('T')[0]}.xlsx`);
};

export const downloadPDF = (transactions: Transaction[], user: User) => {
  const doc = new jsPDF();
  const reportDate = new Date().toLocaleDateString('en-IN');

  doc.setFontSize(22);
  doc.setTextColor(25, 122, 220);
  doc.text('FINTRIX', 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text('SMART FINANCIAL MANAGEMENT', 14, 26);

  doc.line(14, 30, 196, 30);

  doc.setFontSize(11);
  doc.setTextColor(40);
  doc.text('FINANCIAL STATEMENT', 14, 40);

  doc.setFontSize(9);
  doc.text(`Account Holder: ${user.firstName} ${user.lastName}`, 14, 46);
  doc.text(`Report Period: ${reportDate}`, 14, 51);
  doc.text(`Total Transactions: ${transactions.length}`, 14, 56);

  const tableData = transactions.map((tx, index) => [
    index + 1,
    tx.date,
    tx.description,
    tx.category,
    tx.type.charAt(0).toUpperCase() + tx.type.slice(1),
    `Rs. ${tx.amount.toLocaleString('en-IN')}`
  ]);

  autoTable(doc, {
    startY: 65,
    head: [['S.No', 'Date', 'Description', 'Category', 'Type', 'Amount']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [25, 122, 220],
      textColor: [255, 255, 255],
      fontSize: 10,
      fontStyle: 'bold'
    },
    columnStyles: {
      5: { halign: 'right' }
    },
    styles: { fontSize: 9, cellPadding: 3 },
    margin: { top: 20 }
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    doc.text(
      'Generated by Fintrix Dashboard',
      14,
      doc.internal.pageSize.getHeight() - 10
    );
  }

  doc.save(`Fintrix_Statement_${new Date().toISOString().split('T')[0]}.pdf`);
};

export const triggerPrint = () => {
  window.print();
};
