import type { Transaction, User } from '../types';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const transactionsToCSV = (transactions: Transaction[]): string => {
  const headers = ['S.No', 'Date', 'Description', 'Category', 'Type', 'Amount'];
  const rows = transactions.map((tx, index) => [
    index + 1,
    tx.date,
    tx.description.replace(/,/g, ' '),
    tx.category,
    tx.type,
    tx.amount
  ]);

  return [
    headers.join(','),
    ...rows.map(row => row.join(','))
  ].join('\n');
};

export const downloadCSV = (transactions: Transaction[], filename: string = 'Fintrix_Transactions.csv') => {
  const csvContent = transactionsToCSV(transactions);
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const downloadExcel = (transactions: Transaction[], user: User, filename: string = 'Fintrix_Financial_Report') => {
  const reportDate = new Date().toLocaleDateString('en-IN');

  // Prepare data rows
  const dataRows = transactions.map((tx, index) => ({
    'S.No': index + 1,
    'Date': tx.date,
    'Description': tx.description,
    'Category': tx.category,
    'Type': tx.type.toUpperCase(),
    'Amount (Rs.)': tx.amount
  }));

  // Create worksheet
  const ws = XLSX.utils.json_to_sheet(dataRows);

  // Add professional header metadata
  XLSX.utils.sheet_add_aoa(ws, [
    ['FINTRIX FINANCIAL REPORT'],
    ['Generated By:', `${user.firstName} ${user.lastName}`],
    ['Report Date:', reportDate],
    ['']
  ], { origin: 'A1' });

  const range = XLSX.utils.decode_range(ws['!ref'] || 'A1');
  range.s.r = 0;
  ws['!ref'] = XLSX.utils.encode_range(range);

  // Set column widths
  ws['!cols'] = [
    { wch: 8 },
    { wch: 12 },
    { wch: 40 },
    { wch: 15 },
    { wch: 10 },
    { wch: 15 }
  ];

  // Create workbook and download
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Transactions');
  XLSX.writeFile(wb, `${filename}_${new Date().toISOString().split('T')[0]}.xlsx`);
};

export const downloadPDF = (transactions: Transaction[], user: User) => {
  const doc = new jsPDF();
  const reportDate = new Date().toLocaleDateString('en-IN');

  // Add Branded Header
  doc.setFontSize(22);
  doc.setTextColor(25, 122, 220);
  doc.text('FINTRIX', 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text('SMART FINANCIAL MANAGEMENT', 14, 26);

  doc.line(14, 30, 196, 30);

  // Add User Metadata
  doc.setFontSize(11);
  doc.setTextColor(40);
  doc.text('FINANCIAL STATEMENT', 14, 40);

  doc.setFontSize(9);
  doc.text(`Account Holder: ${user.firstName} ${user.lastName}`, 14, 46);
  doc.text(`Report Period: ${reportDate}`, 14, 51);
  doc.text(`Total Transactions: ${transactions.length}`, 14, 56);

  // Generate Table
  const tableData = transactions.map((tx, index) => [
    index + 1,
    tx.date,
    tx.description,
    tx.category,
    tx.type.charAt(0).toUpperCase() + tx.type.slice(1),
    `Rs. ${tx.amount.toLocaleString('en-IN')}`
  ]);

  autoTable(doc, {
    startY: 65,
    head: [['S.No', 'Date', 'Description', 'Category', 'Type', 'Amount']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [25, 122, 220],
      textColor: [255, 255, 255],
      fontSize: 10,
      fontStyle: 'bold'
    },
    columnStyles: {
      5: { halign: 'right' }
    },
    styles: { fontSize: 9, cellPadding: 3 },
    margin: { top: 20 }
  });

  // Add Footer with Page Numbers
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    doc.text(
      'Generated by Fintrix Dashboard',
      14,
      doc.internal.pageSize.getHeight() - 10
    );
  }

  doc.save(`Fintrix_Statement_${new Date().toISOString().split('T')[0]}.pdf`);
};

export const triggerPrint = () => {
  window.print();
};
